name: factory-reset-tools
version: '1.0'
summary: Factory Reset Tools
description: |
  A tool to create reset media and reboot into factory reset menu, for Ubuntu-preinstalled systems.

base: core22
confinement: strict
grade: stable

# for now, only build for amd64, since PC OEM does not have other architectures at the moment...
architectures:
- build-on: [amd64]

apps:
  factory-reset-tools:
    command: factory-reset-tools
    extensions: [gnome]
    plugs:
      - shutdown
      - removable-media
      - block-devices
      - reset-partition-fsuuid
      - reset-yaml
      - udisks2
      - hardware-observe
      - mount-observe
      - dbus-client
  cli:
    command: factory-reset-tools-cli
    plugs:
      - shutdown
      - removable-media
      - block-devices
      - reset-partition-fsuuid
      - reset-yaml
      - udisks2
      - hardware-observe
      - mount-observe
      - dbus-client
  dbus-daemon:
    command: factory-reset-tools-cli dbus
    daemon: simple
    activates-on: [dbus-service]
    plugs:
      - shutdown
      - boot-grub
      - reset-yaml

parts:
  factory-reset-tools:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-build: |
      snapcraftctl build
      dart compile exe -o factory-reset-tools-cli lib/cmdline.dart
      cp factory-reset-tools-cli $CRAFT_PART_INSTALL/
    stage-packages:
      - rsync
      - grub2-common
    build-packages:
      - curl

slots:
  dbus-service:
    interface: dbus
    bus: system
    name: com.canonical.oem.FactoryResetTools

plugs:
  boot-grub:
    interface: system-files
    write:
    - /var/lib/snapd/hostfs/boot/grub
  reset-partition-fsuuid:
    interface: system-files
    read:
    - /etc/reset_partition_fsuuid
  reset-yaml:
    interface: system-files
    read:
    - /usr/share/desktop-provision/reset.yaml
  dbus-client:
    interface: dbus
    bus: system
    name: com.canonical.oem.FactoryResetTools
