name: factory-reset-tools
version: '1.0'
summary: Factory Reset Tools
description: |
  A tool to create reset media and reboot into factory reset menu, for Ubuntu-preinstalled systems.

base: core22
confinement: strict
grade: stable

apps:
  factory-reset-tools:
    command: factory-reset-tools
    extensions: [gnome]
    plugs:
      - shutdown
      - removable-media
      - block-devices
      - boot-grub
      - reset-partition-fsuuid
      - reset-yaml
      - udisks2
      - hardware-observe
      - mount-observe

parts:
  factory-reset-tools:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
      - rsync
      - grub2-common

plugs:
  boot-grub:
    interface: system-files
    write:
    - /boot/grub
  reset-partition-fsuuid:
    interface: system-files
    read:
    - /etc/reset_partition_fsuuid
  reset-yaml:
    interface: system-files
    read:
    - /usr/share/desktop-provision/reset.yaml